#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
REPO_DIR=$(pwd)
BUILD_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

# Overridable variables
QMAKE=/usr/bin/qmake
QMAKE_OPTIONS=""
MAKE=/usr/bin/make
MAKE_OPTIONS="-j$(nproc)"
BUILD_DIR=/tmp/$BUILD_UUID

SETTINGS=build-qt-project
SETTINGS_FILE=/etc/default/$SETTINGS
SETTINGS_OVERRIDES_FILE=$SCRIPT_DIR/../$SETTINGS

# Load variables from settings files
if [ -f $SETTINGS_FILE ]; then
    source $SETTINGS_FILE
fi
if [ -f $SETTINGS_OVERRIDES_FILE ]; then
    source $SETTINGS_OVERRIDES_FILE
fi

if [ -d $BUILD_DIR ]; then
    rm -rf $BUILD_DIR
fi

mkdir $BUILD_DIR
cd $BUILD_DIR

eval $QMAKE $REPO_DIR $QMAKE_OPTIONS
QMAKE_EXIT_CODE="$?"

if [ "$QMAKE_EXIT_CODE" != "0" ]; then
    echo "qmake failed"
    exit $QMAKE_EXIT_CODE
fi

eval $MAKE $MAKE_OPTIONS
MAKE_EXIT_CODE="$?"

if [ "$MAKE_EXIT_CODE" != "0" ]; then
    echo "make failed"
    exit $MAKE_EXIT_CODE
fi

exit 0